// <auto-generated/>
#nullable enable
#pragma warning disable

namespace XFEExtension.NetCore.StringExtension
{
    partial class StringExtension
    {
        /// <remarks>
        /// Pattern:<br/>
        /// <code>^(\\d{3,4}-)?\\d{6,8}$</code><br/>
        /// Explanation:<br/>
        /// <code>
        /// ○ Match if at the beginning of the string.<br/>
        /// ○ Optional (greedy).<br/>
        ///     ○ 1st capture group.<br/>
        ///         ○ Match a Unicode digit atomically at least 3 and at most 4 times.<br/>
        ///         ○ Match '-'.<br/>
        /// ○ Match a Unicode digit atomically at least 6 and at most 8 times.<br/>
        /// ○ Match if at the end of the string or if before an ending newline.<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
        private static partial global::System.Text.RegularExpressions.Regex TelePhoneRegex() => global::System.Text.RegularExpressions.Generated.TelePhoneRegex_0.Instance;
    }
}

namespace XFEExtension.NetCore.StringExtension
{
    partial class StringExtension
    {
        /// <remarks>
        /// Pattern:<br/>
        /// <code>^1[3456789]\\d{9}$</code><br/>
        /// Explanation:<br/>
        /// <code>
        /// ○ Match if at the beginning of the string.<br/>
        /// ○ Match '1'.<br/>
        /// ○ Match a character in the set [3-9].<br/>
        /// ○ Match a Unicode digit exactly 9 times.<br/>
        /// ○ Match if at the end of the string or if before an ending newline.<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
        private static partial global::System.Text.RegularExpressions.Regex MobPhoneNumberRegex() => global::System.Text.RegularExpressions.Generated.MobPhoneNumberRegex_1.Instance;
    }
}

namespace XFEExtension.NetCore.StringExtension
{
    partial class StringExtension
    {
        /// <remarks>
        /// Pattern:<br/>
        /// <code>^\\d{6}$</code><br/>
        /// Explanation:<br/>
        /// <code>
        /// ○ Match if at the beginning of the string.<br/>
        /// ○ Match a Unicode digit exactly 6 times.<br/>
        /// ○ Match if at the end of the string or if before an ending newline.<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
        private static partial global::System.Text.RegularExpressions.Regex PostalCodeRegex() => global::System.Text.RegularExpressions.Generated.PostalCodeRegex_2.Instance;
    }
}

namespace XFEExtension.NetCore.StringExtension
{
    partial class StringExtension
    {
        /// <remarks>
        /// Pattern:<br/>
        /// <code>^[0-9]*$</code><br/>
        /// Explanation:<br/>
        /// <code>
        /// ○ Match if at the beginning of the string.<br/>
        /// ○ Match a character in the set [0-9] atomically any number of times.<br/>
        /// ○ Match if at the end of the string or if before an ending newline.<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
        private static partial global::System.Text.RegularExpressions.Regex NumberRegex() => global::System.Text.RegularExpressions.Generated.NumberRegex_3.Instance;
    }
}

namespace XFEExtension.NetCore.StringExtension
{
    partial class StringExtension
    {
        /// <remarks>
        /// Pattern:<br/>
        /// <code>(^\\d{18}$)|(^\\d{15}$)</code><br/>
        /// Explanation:<br/>
        /// <code>
        /// ○ Match with 2 alternative expressions, atomically.<br/>
        ///     ○ 1st capture group.<br/>
        ///         ○ Match if at the beginning of the string.<br/>
        ///         ○ Match a Unicode digit exactly 18 times.<br/>
        ///         ○ Match if at the end of the string or if before an ending newline.<br/>
        ///     ○ 2nd capture group.<br/>
        ///         ○ Match if at the beginning of the string.<br/>
        ///         ○ Match a Unicode digit exactly 15 times.<br/>
        ///         ○ Match if at the end of the string or if before an ending newline.<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
        private static partial global::System.Text.RegularExpressions.Regex IdCardRegex() => global::System.Text.RegularExpressions.Generated.IdCardRegex_4.Instance;
    }
}

namespace XFEExtension.NetCore.StringExtension
{
    partial class StringExtension
    {
        /// <remarks>
        /// Pattern:<br/>
        /// <code>(?:https?\\:\\/\\/|[wW]{3}\\.)(?:[a-zA-Z0-9\\-]+(?:\\.[a-zA-Z]{2,})+|localhost)(\\:[0-9]{2,})?(?:\\/[^\\s]*)?</code><br/>
        /// Explanation:<br/>
        /// <code>
        /// ○ Match with 2 alternative expressions.<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match the string "http".<br/>
        ///         ○ Match 's' atomically, optionally.<br/>
        ///         ○ Match the string "://".<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [Ww] exactly 3 times.<br/>
        ///         ○ Match '.'.<br/>
        /// ○ Match with 2 alternative expressions.<br/>
        ///     ○ Match a sequence of expressions.<br/>
        ///         ○ Match a character in the set [\-0-9A-Za-z] atomically at least once.<br/>
        ///         ○ Loop greedily at least once.<br/>
        ///             ○ Match '.'.<br/>
        ///             ○ Match an ASCII letter greedily at least twice.<br/>
        ///     ○ Match the string "localhost".<br/>
        /// ○ Optional (greedy).<br/>
        ///     ○ 1st capture group.<br/>
        ///         ○ Match ':'.<br/>
        ///         ○ Match a character in the set [0-9] greedily at least twice.<br/>
        /// ○ Optional (greedy).<br/>
        ///     ○ Match '/'.<br/>
        ///     ○ Match any character other than a whitespace character atomically any number of times.<br/>
        /// </code>
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
        private static partial global::System.Text.RegularExpressions.Regex UrlRegex() => global::System.Text.RegularExpressions.Generated.UrlRegex_5.Instance;
    }
}

namespace System.Text.RegularExpressions.Generated
{
    using System;
    using System.Buffers;
    using System.CodeDom.Compiler;
    using System.Collections;
    using System.ComponentModel;
    using System.Globalization;
    using System.Runtime.CompilerServices;
    using System.Text.RegularExpressions;
    using System.Threading;

    /// <summary>Custom <see cref="Regex"/>-derived type for the TelePhoneRegex method.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
    file sealed class TelePhoneRegex_0 : Regex
    {
        /// <summary>Cached, thread-safe singleton instance.</summary>
        internal static readonly TelePhoneRegex_0 Instance = new();
    
        /// <summary>Initializes the instance.</summary>
        private TelePhoneRegex_0()
        {
            base.pattern = "^(\\d{3,4}-)?\\d{6,8}$";
            base.roptions = RegexOptions.None;
            ValidateMatchTimeout(Utilities.s_defaultTimeout);
            base.internalMatchTimeout = Utilities.s_defaultTimeout;
            base.factory = new RunnerFactory();
            base.capsize = 2;
        }
            
        /// <summary>Provides a factory for creating <see cref="RegexRunner"/> instances to be used by methods on <see cref="Regex"/>.</summary>
        private sealed class RunnerFactory : RegexRunnerFactory
        {
            /// <summary>Creates an instance of a <see cref="RegexRunner"/> used by methods on <see cref="Regex"/>.</summary>
            protected override RegexRunner CreateInstance() => new Runner();
        
            /// <summary>Provides the runner that contains the custom logic implementing the specified regular expression.</summary>
            private sealed class Runner : RegexRunner
            {
                /// <summary>Scan the <paramref name="inputSpan"/> starting from base.runtextstart for the next match.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                protected override void Scan(ReadOnlySpan<char> inputSpan)
                {
                    // The pattern is anchored.  Validate the current position and try to match at it only.
                    if (TryFindNextPossibleStartingPosition(inputSpan) && !TryMatchAtCurrentPosition(inputSpan))
                    {
                        base.runtextpos = inputSpan.Length;
                    }
                }
        
                /// <summary>Search <paramref name="inputSpan"/> starting from base.runtextpos for the next location a match could possibly start.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if a possible match was found; false if no more matches are possible.</returns>
                private bool TryFindNextPossibleStartingPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    
                    // Any possible match is at least 6 characters.
                    if (pos <= inputSpan.Length - 6)
                    {
                        // The pattern leads with a beginning (\A) anchor.
                        if (pos == 0)
                        {
                            return true;
                        }
                    }
                    
                    // No match found.
                    base.runtextpos = inputSpan.Length;
                    return false;
                }
        
                /// <summary>Determine whether <paramref name="inputSpan"/> at base.runtextpos is a match for the regular expression.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if the regular expression matches at the current position; otherwise, false.</returns>
                private bool TryMatchAtCurrentPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    int matchStart = pos;
                    int loop_iteration = 0;
                    int stackpos = 0;
                    ReadOnlySpan<char> slice = inputSpan.Slice(pos);
                    
                    // Match if at the beginning of the string.
                    if (pos != 0)
                    {
                        UncaptureUntil(0);
                        return false; // The input didn't match.
                    }
                    
                    // Optional (greedy).
                    //{
                        loop_iteration = 0;
                        
                        LoopBody:
                        Utilities.StackPush(ref base.runstack!, ref stackpos, base.Crawlpos(), pos);
                        
                        loop_iteration++;
                        
                        // 1st capture group.
                        {
                            int capture_starting_pos = pos;
                            
                            // Match a Unicode digit atomically at least 3 and at most 4 times.
                            {
                                int iteration = 0;
                                while (iteration < 4 && (uint)iteration < (uint)slice.Length && char.IsDigit(slice[iteration]))
                                {
                                    iteration++;
                                }
                                
                                if (iteration < 3)
                                {
                                    goto LoopIterationNoMatch;
                                }
                                
                                slice = slice.Slice(iteration);
                                pos += iteration;
                            }
                            
                            // Match '-'.
                            if (slice.IsEmpty || slice[0] != '-')
                            {
                                goto LoopIterationNoMatch;
                            }
                            
                            pos++;
                            slice = inputSpan.Slice(pos);
                            base.Capture(1, capture_starting_pos, pos);
                        }
                        
                        
                        // The loop has an upper bound of 1. Continue iterating greedily if it hasn't yet been reached.
                        if (loop_iteration == 0)
                        {
                            goto LoopBody;
                        }
                        goto LoopEnd;
                        
                        // The loop iteration failed. Put state back to the way it was before the iteration.
                        LoopIterationNoMatch:
                        if (--loop_iteration < 0)
                        {
                            // Unable to match the remainder of the expression after exhausting the loop.
                            UncaptureUntil(0);
                            return false; // The input didn't match.
                        }
                        pos = base.runstack![--stackpos];
                        UncaptureUntil(base.runstack![--stackpos]);
                        slice = inputSpan.Slice(pos);
                        LoopEnd:;
                    //}
                    
                    // Match a Unicode digit atomically at least 6 and at most 8 times.
                    {
                        int iteration1 = 0;
                        while (iteration1 < 8 && (uint)iteration1 < (uint)slice.Length && char.IsDigit(slice[iteration1]))
                        {
                            iteration1++;
                        }
                        
                        if (iteration1 < 6)
                        {
                            goto LoopIterationNoMatch;
                        }
                        
                        slice = slice.Slice(iteration1);
                        pos += iteration1;
                    }
                    
                    // Match if at the end of the string or if before an ending newline.
                    if (pos < inputSpan.Length - 1 || ((uint)pos < (uint)inputSpan.Length && inputSpan[pos] != '\n'))
                    {
                        goto LoopIterationNoMatch;
                    }
                    
                    // The input matched.
                    base.runtextpos = pos;
                    base.Capture(0, matchStart, pos);
                    return true;
                    
                    // <summary>Undo captures until it reaches the specified capture position.</summary>
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    void UncaptureUntil(int capturePosition)
                    {
                        while (base.Crawlpos() > capturePosition)
                        {
                            base.Uncapture();
                        }
                    }
                }
            }
        }

    }
    
    /// <summary>Custom <see cref="Regex"/>-derived type for the MobPhoneNumberRegex method.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
    file sealed class MobPhoneNumberRegex_1 : Regex
    {
        /// <summary>Cached, thread-safe singleton instance.</summary>
        internal static readonly MobPhoneNumberRegex_1 Instance = new();
    
        /// <summary>Initializes the instance.</summary>
        private MobPhoneNumberRegex_1()
        {
            base.pattern = "^1[3456789]\\d{9}$";
            base.roptions = RegexOptions.None;
            ValidateMatchTimeout(Utilities.s_defaultTimeout);
            base.internalMatchTimeout = Utilities.s_defaultTimeout;
            base.factory = new RunnerFactory();
            base.capsize = 1;
        }
            
        /// <summary>Provides a factory for creating <see cref="RegexRunner"/> instances to be used by methods on <see cref="Regex"/>.</summary>
        private sealed class RunnerFactory : RegexRunnerFactory
        {
            /// <summary>Creates an instance of a <see cref="RegexRunner"/> used by methods on <see cref="Regex"/>.</summary>
            protected override RegexRunner CreateInstance() => new Runner();
        
            /// <summary>Provides the runner that contains the custom logic implementing the specified regular expression.</summary>
            private sealed class Runner : RegexRunner
            {
                /// <summary>Scan the <paramref name="inputSpan"/> starting from base.runtextstart for the next match.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                protected override void Scan(ReadOnlySpan<char> inputSpan)
                {
                    // The pattern is anchored.  Validate the current position and try to match at it only.
                    if (TryFindNextPossibleStartingPosition(inputSpan) && !TryMatchAtCurrentPosition(inputSpan))
                    {
                        base.runtextpos = inputSpan.Length;
                    }
                }
        
                /// <summary>Search <paramref name="inputSpan"/> starting from base.runtextpos for the next location a match could possibly start.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if a possible match was found; false if no more matches are possible.</returns>
                private bool TryFindNextPossibleStartingPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    
                    // Any possible match is at least 11 characters.
                    if (pos <= inputSpan.Length - 11)
                    {
                        // The pattern leads with a beginning (\A) anchor.
                        if (pos == 0)
                        {
                            return true;
                        }
                    }
                    
                    // No match found.
                    base.runtextpos = inputSpan.Length;
                    return false;
                }
        
                /// <summary>Determine whether <paramref name="inputSpan"/> at base.runtextpos is a match for the regular expression.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if the regular expression matches at the current position; otherwise, false.</returns>
                private bool TryMatchAtCurrentPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    int matchStart = pos;
                    ReadOnlySpan<char> slice = inputSpan.Slice(pos);
                    
                    // Match if at the beginning of the string.
                    if (pos != 0)
                    {
                        return false; // The input didn't match.
                    }
                    
                    if ((uint)slice.Length < 11 ||
                        slice[0] != '1' || // Match '1'.
                        !char.IsBetween(slice[1], '3', '9') || // Match a character in the set [3-9].
                        !char.IsDigit(slice[2]) || // Match a Unicode digit exactly 9 times.
                        !char.IsDigit(slice[3]) ||
                        !char.IsDigit(slice[4]) ||
                        !char.IsDigit(slice[5]) ||
                        !char.IsDigit(slice[6]) ||
                        !char.IsDigit(slice[7]) ||
                        !char.IsDigit(slice[8]) ||
                        !char.IsDigit(slice[9]) ||
                        !char.IsDigit(slice[10]))
                    {
                        return false; // The input didn't match.
                    }
                    
                    // Match if at the end of the string or if before an ending newline.
                    if (12 < slice.Length || (11 < slice.Length && slice[11] != '\n'))
                    {
                        return false; // The input didn't match.
                    }
                    
                    // The input matched.
                    pos += 11;
                    base.runtextpos = pos;
                    base.Capture(0, matchStart, pos);
                    return true;
                }
            }
        }

    }
    
    /// <summary>Custom <see cref="Regex"/>-derived type for the PostalCodeRegex method.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
    file sealed class PostalCodeRegex_2 : Regex
    {
        /// <summary>Cached, thread-safe singleton instance.</summary>
        internal static readonly PostalCodeRegex_2 Instance = new();
    
        /// <summary>Initializes the instance.</summary>
        private PostalCodeRegex_2()
        {
            base.pattern = "^\\d{6}$";
            base.roptions = RegexOptions.None;
            ValidateMatchTimeout(Utilities.s_defaultTimeout);
            base.internalMatchTimeout = Utilities.s_defaultTimeout;
            base.factory = new RunnerFactory();
            base.capsize = 1;
        }
            
        /// <summary>Provides a factory for creating <see cref="RegexRunner"/> instances to be used by methods on <see cref="Regex"/>.</summary>
        private sealed class RunnerFactory : RegexRunnerFactory
        {
            /// <summary>Creates an instance of a <see cref="RegexRunner"/> used by methods on <see cref="Regex"/>.</summary>
            protected override RegexRunner CreateInstance() => new Runner();
        
            /// <summary>Provides the runner that contains the custom logic implementing the specified regular expression.</summary>
            private sealed class Runner : RegexRunner
            {
                /// <summary>Scan the <paramref name="inputSpan"/> starting from base.runtextstart for the next match.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                protected override void Scan(ReadOnlySpan<char> inputSpan)
                {
                    // The pattern is anchored.  Validate the current position and try to match at it only.
                    if (TryFindNextPossibleStartingPosition(inputSpan) && !TryMatchAtCurrentPosition(inputSpan))
                    {
                        base.runtextpos = inputSpan.Length;
                    }
                }
        
                /// <summary>Search <paramref name="inputSpan"/> starting from base.runtextpos for the next location a match could possibly start.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if a possible match was found; false if no more matches are possible.</returns>
                private bool TryFindNextPossibleStartingPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    
                    // Any possible match is at least 6 characters.
                    if (pos <= inputSpan.Length - 6)
                    {
                        // The pattern leads with a beginning (\A) anchor.
                        if (pos == 0)
                        {
                            return true;
                        }
                    }
                    
                    // No match found.
                    base.runtextpos = inputSpan.Length;
                    return false;
                }
        
                /// <summary>Determine whether <paramref name="inputSpan"/> at base.runtextpos is a match for the regular expression.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if the regular expression matches at the current position; otherwise, false.</returns>
                private bool TryMatchAtCurrentPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    int matchStart = pos;
                    ReadOnlySpan<char> slice = inputSpan.Slice(pos);
                    
                    // Match if at the beginning of the string.
                    if (pos != 0)
                    {
                        return false; // The input didn't match.
                    }
                    
                    // Match a Unicode digit exactly 6 times.
                    {
                        if ((uint)slice.Length < 6 ||
                            !char.IsDigit(slice[0]) ||
                            !char.IsDigit(slice[1]) ||
                            !char.IsDigit(slice[2]) ||
                            !char.IsDigit(slice[3]) ||
                            !char.IsDigit(slice[4]) ||
                            !char.IsDigit(slice[5]))
                        {
                            return false; // The input didn't match.
                        }
                    }
                    
                    // Match if at the end of the string or if before an ending newline.
                    if (7 < slice.Length || (6 < slice.Length && slice[6] != '\n'))
                    {
                        return false; // The input didn't match.
                    }
                    
                    // The input matched.
                    pos += 6;
                    base.runtextpos = pos;
                    base.Capture(0, matchStart, pos);
                    return true;
                }
            }
        }

    }
    
    /// <summary>Custom <see cref="Regex"/>-derived type for the NumberRegex method.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
    file sealed class NumberRegex_3 : Regex
    {
        /// <summary>Cached, thread-safe singleton instance.</summary>
        internal static readonly NumberRegex_3 Instance = new();
    
        /// <summary>Initializes the instance.</summary>
        private NumberRegex_3()
        {
            base.pattern = "^[0-9]*$";
            base.roptions = RegexOptions.None;
            ValidateMatchTimeout(Utilities.s_defaultTimeout);
            base.internalMatchTimeout = Utilities.s_defaultTimeout;
            base.factory = new RunnerFactory();
            base.capsize = 1;
        }
            
        /// <summary>Provides a factory for creating <see cref="RegexRunner"/> instances to be used by methods on <see cref="Regex"/>.</summary>
        private sealed class RunnerFactory : RegexRunnerFactory
        {
            /// <summary>Creates an instance of a <see cref="RegexRunner"/> used by methods on <see cref="Regex"/>.</summary>
            protected override RegexRunner CreateInstance() => new Runner();
        
            /// <summary>Provides the runner that contains the custom logic implementing the specified regular expression.</summary>
            private sealed class Runner : RegexRunner
            {
                /// <summary>Scan the <paramref name="inputSpan"/> starting from base.runtextstart for the next match.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                protected override void Scan(ReadOnlySpan<char> inputSpan)
                {
                    // The pattern is anchored.  Validate the current position and try to match at it only.
                    if (TryFindNextPossibleStartingPosition(inputSpan) && !TryMatchAtCurrentPosition(inputSpan))
                    {
                        base.runtextpos = inputSpan.Length;
                    }
                }
        
                /// <summary>Search <paramref name="inputSpan"/> starting from base.runtextpos for the next location a match could possibly start.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if a possible match was found; false if no more matches are possible.</returns>
                private bool TryFindNextPossibleStartingPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    
                    // The pattern leads with a beginning (\A) anchor.
                    if (pos == 0)
                    {
                        return true;
                    }
                    
                    // No match found.
                    base.runtextpos = inputSpan.Length;
                    return false;
                }
        
                /// <summary>Determine whether <paramref name="inputSpan"/> at base.runtextpos is a match for the regular expression.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if the regular expression matches at the current position; otherwise, false.</returns>
                private bool TryMatchAtCurrentPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    int matchStart = pos;
                    ReadOnlySpan<char> slice = inputSpan.Slice(pos);
                    
                    // Match if at the beginning of the string.
                    if (pos != 0)
                    {
                        return false; // The input didn't match.
                    }
                    
                    // Match a character in the set [0-9] atomically any number of times.
                    {
                        int iteration = slice.IndexOfAnyExceptInRange('0', '9');
                        if (iteration < 0)
                        {
                            iteration = slice.Length;
                        }
                        
                        slice = slice.Slice(iteration);
                        pos += iteration;
                    }
                    
                    // Match if at the end of the string or if before an ending newline.
                    if (pos < inputSpan.Length - 1 || ((uint)pos < (uint)inputSpan.Length && inputSpan[pos] != '\n'))
                    {
                        return false; // The input didn't match.
                    }
                    
                    // The input matched.
                    base.runtextpos = pos;
                    base.Capture(0, matchStart, pos);
                    return true;
                }
            }
        }

    }
    
    /// <summary>Custom <see cref="Regex"/>-derived type for the IdCardRegex method.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
    file sealed class IdCardRegex_4 : Regex
    {
        /// <summary>Cached, thread-safe singleton instance.</summary>
        internal static readonly IdCardRegex_4 Instance = new();
    
        /// <summary>Initializes the instance.</summary>
        private IdCardRegex_4()
        {
            base.pattern = "(^\\d{18}$)|(^\\d{15}$)";
            base.roptions = RegexOptions.None;
            ValidateMatchTimeout(Utilities.s_defaultTimeout);
            base.internalMatchTimeout = Utilities.s_defaultTimeout;
            base.factory = new RunnerFactory();
            base.capsize = 3;
        }
            
        /// <summary>Provides a factory for creating <see cref="RegexRunner"/> instances to be used by methods on <see cref="Regex"/>.</summary>
        private sealed class RunnerFactory : RegexRunnerFactory
        {
            /// <summary>Creates an instance of a <see cref="RegexRunner"/> used by methods on <see cref="Regex"/>.</summary>
            protected override RegexRunner CreateInstance() => new Runner();
        
            /// <summary>Provides the runner that contains the custom logic implementing the specified regular expression.</summary>
            private sealed class Runner : RegexRunner
            {
                /// <summary>Scan the <paramref name="inputSpan"/> starting from base.runtextstart for the next match.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                protected override void Scan(ReadOnlySpan<char> inputSpan)
                {
                    // The pattern is anchored.  Validate the current position and try to match at it only.
                    if (TryFindNextPossibleStartingPosition(inputSpan) && !TryMatchAtCurrentPosition(inputSpan))
                    {
                        base.runtextpos = inputSpan.Length;
                    }
                }
        
                /// <summary>Search <paramref name="inputSpan"/> starting from base.runtextpos for the next location a match could possibly start.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if a possible match was found; false if no more matches are possible.</returns>
                private bool TryFindNextPossibleStartingPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    
                    // Any possible match is at least 15 characters.
                    if (pos <= inputSpan.Length - 15)
                    {
                        // The pattern leads with a beginning (\A) anchor.
                        if (pos == 0)
                        {
                            return true;
                        }
                    }
                    
                    // No match found.
                    base.runtextpos = inputSpan.Length;
                    return false;
                }
        
                /// <summary>Determine whether <paramref name="inputSpan"/> at base.runtextpos is a match for the regular expression.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if the regular expression matches at the current position; otherwise, false.</returns>
                private bool TryMatchAtCurrentPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    int matchStart = pos;
                    int capture_starting_pos = 0;
                    int capture_starting_pos1 = 0;
                    ReadOnlySpan<char> slice = inputSpan.Slice(pos);
                    
                    // Match with 2 alternative expressions, atomically.
                    {
                        int alternation_starting_pos = pos;
                        int alternation_starting_capturepos = base.Crawlpos();
                        
                        // Branch 0
                        {
                            // 1st capture group.
                            {
                                capture_starting_pos = pos;
                                
                                // Match if at the beginning of the string.
                                if (pos != 0)
                                {
                                    goto AlternationBranch;
                                }
                                
                                // Match a Unicode digit exactly 18 times.
                                {
                                    if ((uint)slice.Length < 18)
                                    {
                                        goto AlternationBranch;
                                    }
                                    
                                    ReadOnlySpan<char> repeaterSlice = slice.Slice(0, 18);
                                    for (int i = 0; i < repeaterSlice.Length; i++)
                                    {
                                        if (!char.IsDigit(repeaterSlice[i]))
                                        {
                                            goto AlternationBranch;
                                        }
                                    }
                                }
                                
                                // Match if at the end of the string or if before an ending newline.
                                if (19 < slice.Length || (18 < slice.Length && slice[18] != '\n'))
                                {
                                    goto AlternationBranch;
                                }
                                
                                pos += 18;
                                slice = inputSpan.Slice(pos);
                                base.Capture(1, capture_starting_pos, pos);
                            }
                            
                            goto AlternationMatch;
                            
                            AlternationBranch:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                            UncaptureUntil(alternation_starting_capturepos);
                        }
                        
                        // Branch 1
                        {
                            // 2nd capture group.
                            {
                                capture_starting_pos1 = pos;
                                
                                // Match if at the beginning of the string.
                                if (pos != 0)
                                {
                                    UncaptureUntil(0);
                                    return false; // The input didn't match.
                                }
                                
                                // Match a Unicode digit exactly 15 times.
                                {
                                    if ((uint)slice.Length < 15 ||
                                        !char.IsDigit(slice[0]) ||
                                        !char.IsDigit(slice[1]) ||
                                        !char.IsDigit(slice[2]) ||
                                        !char.IsDigit(slice[3]) ||
                                        !char.IsDigit(slice[4]) ||
                                        !char.IsDigit(slice[5]) ||
                                        !char.IsDigit(slice[6]) ||
                                        !char.IsDigit(slice[7]) ||
                                        !char.IsDigit(slice[8]) ||
                                        !char.IsDigit(slice[9]) ||
                                        !char.IsDigit(slice[10]) ||
                                        !char.IsDigit(slice[11]) ||
                                        !char.IsDigit(slice[12]) ||
                                        !char.IsDigit(slice[13]) ||
                                        !char.IsDigit(slice[14]))
                                    {
                                        UncaptureUntil(0);
                                        return false; // The input didn't match.
                                    }
                                }
                                
                                // Match if at the end of the string or if before an ending newline.
                                if (16 < slice.Length || (15 < slice.Length && slice[15] != '\n'))
                                {
                                    UncaptureUntil(0);
                                    return false; // The input didn't match.
                                }
                                
                                pos += 15;
                                slice = inputSpan.Slice(pos);
                                base.Capture(2, capture_starting_pos1, pos);
                            }
                            
                        }
                        
                        AlternationMatch:;
                    }
                    
                    // The input matched.
                    base.runtextpos = pos;
                    base.Capture(0, matchStart, pos);
                    return true;
                    
                    // <summary>Undo captures until it reaches the specified capture position.</summary>
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    void UncaptureUntil(int capturePosition)
                    {
                        while (base.Crawlpos() > capturePosition)
                        {
                            base.Uncapture();
                        }
                    }
                }
            }
        }

    }
    
    /// <summary>Custom <see cref="Regex"/>-derived type for the UrlRegex method.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
    file sealed class UrlRegex_5 : Regex
    {
        /// <summary>Cached, thread-safe singleton instance.</summary>
        internal static readonly UrlRegex_5 Instance = new();
    
        /// <summary>Initializes the instance.</summary>
        private UrlRegex_5()
        {
            base.pattern = "(?:https?\\:\\/\\/|[wW]{3}\\.)(?:[a-zA-Z0-9\\-]+(?:\\.[a-zA-Z]{2,})+|localhost)(\\:[0-9]{2,})?(?:\\/[^\\s]*)?";
            base.roptions = RegexOptions.None;
            ValidateMatchTimeout(Utilities.s_defaultTimeout);
            base.internalMatchTimeout = Utilities.s_defaultTimeout;
            base.factory = new RunnerFactory();
            base.capsize = 2;
        }
            
        /// <summary>Provides a factory for creating <see cref="RegexRunner"/> instances to be used by methods on <see cref="Regex"/>.</summary>
        private sealed class RunnerFactory : RegexRunnerFactory
        {
            /// <summary>Creates an instance of a <see cref="RegexRunner"/> used by methods on <see cref="Regex"/>.</summary>
            protected override RegexRunner CreateInstance() => new Runner();
        
            /// <summary>Provides the runner that contains the custom logic implementing the specified regular expression.</summary>
            private sealed class Runner : RegexRunner
            {
                /// <summary>Scan the <paramref name="inputSpan"/> starting from base.runtextstart for the next match.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                protected override void Scan(ReadOnlySpan<char> inputSpan)
                {
                    // Search until we can't find a valid starting position, we find a match, or we reach the end of the input.
                    while (TryFindNextPossibleStartingPosition(inputSpan) &&
                           !TryMatchAtCurrentPosition(inputSpan) &&
                           base.runtextpos != inputSpan.Length)
                    {
                        base.runtextpos++;
                        if (Utilities.s_hasTimeout)
                        {
                            base.CheckTimeout();
                        }
                    }
                }
        
                /// <summary>Search <paramref name="inputSpan"/> starting from base.runtextpos for the next location a match could possibly start.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if a possible match was found; false if no more matches are possible.</returns>
                private bool TryFindNextPossibleStartingPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    char ch;
                    
                    // Any possible match is at least 8 characters.
                    if (pos <= inputSpan.Length - 8)
                    {
                        // The pattern begins with a character in the set [Whw].
                        // Find the next occurrence. If it can't be found, there's no match.
                        ReadOnlySpan<char> span = inputSpan.Slice(pos);
                        for (int i = 0; i < span.Length - 7; i++)
                        {
                            int indexOfPos = span.Slice(i).IndexOfAny('W', 'h', 'w');
                            if (indexOfPos < 0)
                            {
                                goto NoMatchFound;
                            }
                            i += indexOfPos;
                            
                            // The primary set being searched for was found. 2 more sets will be checked so as
                            // to minimize the number of places TryMatchAtCurrentPosition is run unnecessarily.
                            // Make sure they fit in the remainder of the input.
                            if ((uint)(i + 3) >= (uint)span.Length)
                            {
                                goto NoMatchFound;
                            }
                            
                            if ((((ch = span[i + 3]) == '.') | (ch == 'p')) &&
                                (((ch = span[i + 1]) == 'W') | (ch == 't') | (ch == 'w')))
                            {
                                base.runtextpos = pos + i;
                                return true;
                            }
                        }
                    }
                    
                    // No match found.
                    NoMatchFound:
                    base.runtextpos = inputSpan.Length;
                    return false;
                }
        
                /// <summary>Determine whether <paramref name="inputSpan"/> at base.runtextpos is a match for the regular expression.</summary>
                /// <param name="inputSpan">The text being scanned by the regular expression.</param>
                /// <returns>true if the regular expression matches at the current position; otherwise, false.</returns>
                private bool TryMatchAtCurrentPosition(ReadOnlySpan<char> inputSpan)
                {
                    int pos = base.runtextpos;
                    int matchStart = pos;
                    int alternation_branch = 0;
                    int alternation_starting_capturepos = 0;
                    int alternation_starting_pos = 0;
                    int charloop_starting_pos = 0, charloop_ending_pos = 0;
                    int charloop_starting_pos1 = 0, charloop_ending_pos1 = 0;
                    int loop_iteration = 0;
                    int loop_iteration1 = 0;
                    int loop_iteration2 = 0;
                    int stackpos = 0;
                    int startingStackpos = 0;
                    ReadOnlySpan<char> slice = inputSpan.Slice(pos);
                    
                    // Match with 2 alternative expressions.
                    //{
                        if (slice.IsEmpty)
                        {
                            UncaptureUntil(0);
                            return false; // The input didn't match.
                        }
                        
                        switch (slice[0])
                        {
                            case 'h':
                                // Match the string "ttp".
                                if (!slice.Slice(1).StartsWith("ttp"))
                                {
                                    UncaptureUntil(0);
                                    return false; // The input didn't match.
                                }
                                
                                // Match 's' atomically, optionally.
                                {
                                    if ((uint)slice.Length > (uint)4 && slice[4] == 's')
                                    {
                                        slice = slice.Slice(1);
                                        pos++;
                                    }
                                }
                                
                                // Match the string "://".
                                if (!slice.Slice(4).StartsWith("://"))
                                {
                                    UncaptureUntil(0);
                                    return false; // The input didn't match.
                                }
                                
                                pos += 7;
                                slice = inputSpan.Slice(pos);
                                break;
                                
                            case 'W' or 'w':
                                if ((uint)slice.Length < 4 ||
                                    !slice.StartsWith("www.", StringComparison.OrdinalIgnoreCase)) // Match the string "www." (ordinal case-insensitive)
                                {
                                    UncaptureUntil(0);
                                    return false; // The input didn't match.
                                }
                                
                                pos += 4;
                                slice = inputSpan.Slice(pos);
                                break;
                                
                            default:
                                UncaptureUntil(0);
                                return false; // The input didn't match.
                        }
                    //}
                    
                    // Match with 2 alternative expressions.
                    //{
                        alternation_starting_pos = pos;
                        alternation_starting_capturepos = base.Crawlpos();
                        
                        // Branch 0
                        //{
                            // Match a character in the set [\-0-9A-Za-z] atomically at least once.
                            {
                                int iteration = slice.IndexOfAnyExcept(Utilities.s_asciiLettersAndDigitsAndDash);
                                if (iteration < 0)
                                {
                                    iteration = slice.Length;
                                }
                                
                                if (iteration == 0)
                                {
                                    goto AlternationBranch;
                                }
                                
                                slice = slice.Slice(iteration);
                                pos += iteration;
                            }
                            
                            // Loop greedily at least once.
                            //{
                                loop_iteration = 0;
                                
                                LoopBody:
                                Utilities.StackPush(ref base.runstack!, ref stackpos, base.Crawlpos(), pos);
                                
                                loop_iteration++;
                                
                                // Match '.'.
                                if (slice.IsEmpty || slice[0] != '.')
                                {
                                    goto LoopIterationNoMatch;
                                }
                                
                                // Match an ASCII letter greedily at least twice.
                                //{
                                    pos++;
                                    slice = inputSpan.Slice(pos);
                                    charloop_starting_pos = pos;
                                    
                                    int iteration1 = slice.IndexOfAnyExcept(Utilities.s_asciiLetters);
                                    if (iteration1 < 0)
                                    {
                                        iteration1 = slice.Length;
                                    }
                                    
                                    if (iteration1 < 2)
                                    {
                                        goto LoopIterationNoMatch;
                                    }
                                    
                                    slice = slice.Slice(iteration1);
                                    pos += iteration1;
                                    
                                    charloop_ending_pos = pos;
                                    charloop_starting_pos += 2;
                                    goto CharLoopEnd;
                                    
                                    CharLoopBacktrack:
                                    UncaptureUntil(base.runstack![--stackpos]);
                                    Utilities.StackPop(base.runstack!, ref stackpos, out charloop_ending_pos, out charloop_starting_pos);
                                    
                                    if (Utilities.s_hasTimeout)
                                    {
                                        base.CheckTimeout();
                                    }
                                    
                                    if (charloop_starting_pos >= charloop_ending_pos)
                                    {
                                        goto LoopIterationNoMatch;
                                    }
                                    pos = --charloop_ending_pos;
                                    slice = inputSpan.Slice(pos);
                                    
                                    CharLoopEnd:
                                    Utilities.StackPush(ref base.runstack!, ref stackpos, charloop_starting_pos, charloop_ending_pos, base.Crawlpos());
                                //}
                                
                                
                                // The loop has no upper bound. Continue iterating greedily.
                                goto LoopBody;
                                
                                // The loop iteration failed. Put state back to the way it was before the iteration.
                                LoopIterationNoMatch:
                                if (--loop_iteration < 0)
                                {
                                    // Unable to match the remainder of the expression after exhausting the loop.
                                    goto AlternationBranch;
                                }
                                pos = base.runstack![--stackpos];
                                UncaptureUntil(base.runstack![--stackpos]);
                                slice = inputSpan.Slice(pos);
                                if (loop_iteration == 0)
                                {
                                    // No iterations have been matched to backtrack into. Fail the loop.
                                    goto AlternationBranch;
                                }
                                
                                goto LoopEnd;
                                
                                LoopBacktrack:
                                if (Utilities.s_hasTimeout)
                                {
                                    base.CheckTimeout();
                                }
                                
                                if (loop_iteration == 0)
                                {
                                    // No iterations of the loop remain to backtrack into. Fail the loop.
                                    goto AlternationBranch;
                                }
                                goto CharLoopBacktrack;
                                LoopEnd:;
                            //}
                            
                            alternation_branch = 0;
                            goto AlternationMatch;
                            
                            AlternationBranch:
                            pos = alternation_starting_pos;
                            slice = inputSpan.Slice(pos);
                            UncaptureUntil(alternation_starting_capturepos);
                        //}
                        
                        // Branch 1
                        //{
                            // Match the string "localhost".
                            if (!slice.StartsWith("localhost"))
                            {
                                UncaptureUntil(0);
                                return false; // The input didn't match.
                            }
                            
                            alternation_branch = 1;
                            pos += 9;
                            slice = inputSpan.Slice(pos);
                            goto AlternationMatch;
                        //}
                        
                        AlternationBacktrack:
                        if (Utilities.s_hasTimeout)
                        {
                            base.CheckTimeout();
                        }
                        
                        switch (alternation_branch)
                        {
                            case 0:
                                goto LoopBacktrack;
                            case 1:
                                UncaptureUntil(0);
                                return false; // The input didn't match.
                        }
                        
                        AlternationMatch:;
                    //}
                    
                    // Optional (greedy).
                    //{
                        loop_iteration1 = 0;
                        
                        LoopBody1:
                        Utilities.StackPush(ref base.runstack!, ref stackpos, base.Crawlpos(), pos);
                        
                        loop_iteration1++;
                        
                        // 1st capture group.
                        //{
                            int capture_starting_pos = pos;
                            
                            // Match ':'.
                            if (slice.IsEmpty || slice[0] != ':')
                            {
                                goto LoopIterationNoMatch1;
                            }
                            
                            // Match a character in the set [0-9] greedily at least twice.
                            //{
                                pos++;
                                slice = inputSpan.Slice(pos);
                                charloop_starting_pos1 = pos;
                                
                                int iteration2 = slice.IndexOfAnyExceptInRange('0', '9');
                                if (iteration2 < 0)
                                {
                                    iteration2 = slice.Length;
                                }
                                
                                if (iteration2 < 2)
                                {
                                    goto LoopIterationNoMatch1;
                                }
                                
                                slice = slice.Slice(iteration2);
                                pos += iteration2;
                                
                                charloop_ending_pos1 = pos;
                                charloop_starting_pos1 += 2;
                                goto CharLoopEnd1;
                                
                                CharLoopBacktrack1:
                                UncaptureUntil(base.runstack![--stackpos]);
                                Utilities.StackPop(base.runstack!, ref stackpos, out charloop_ending_pos1, out charloop_starting_pos1);
                                
                                if (Utilities.s_hasTimeout)
                                {
                                    base.CheckTimeout();
                                }
                                
                                if (charloop_starting_pos1 >= charloop_ending_pos1)
                                {
                                    goto LoopIterationNoMatch1;
                                }
                                pos = --charloop_ending_pos1;
                                slice = inputSpan.Slice(pos);
                                
                                CharLoopEnd1:
                                Utilities.StackPush(ref base.runstack!, ref stackpos, charloop_starting_pos1, charloop_ending_pos1, base.Crawlpos());
                            //}
                            
                            base.Capture(1, capture_starting_pos, pos);
                            
                            Utilities.StackPush(ref base.runstack!, ref stackpos, capture_starting_pos);
                            goto CaptureSkipBacktrack;
                            
                            CaptureBacktrack:
                            capture_starting_pos = base.runstack![--stackpos];
                            goto CharLoopBacktrack1;
                            
                            CaptureSkipBacktrack:;
                        //}
                        
                        
                        // The loop has an upper bound of 1. Continue iterating greedily if it hasn't yet been reached.
                        if (loop_iteration1 == 0)
                        {
                            goto LoopBody1;
                        }
                        goto LoopEnd1;
                        
                        // The loop iteration failed. Put state back to the way it was before the iteration.
                        LoopIterationNoMatch1:
                        if (--loop_iteration1 < 0)
                        {
                            // Unable to match the remainder of the expression after exhausting the loop.
                            goto AlternationBacktrack;
                        }
                        pos = base.runstack![--stackpos];
                        UncaptureUntil(base.runstack![--stackpos]);
                        slice = inputSpan.Slice(pos);
                        goto LoopEnd1;
                        
                        LoopBacktrack1:
                        if (Utilities.s_hasTimeout)
                        {
                            base.CheckTimeout();
                        }
                        
                        if (loop_iteration1 == 0)
                        {
                            // No iterations of the loop remain to backtrack into. Fail the loop.
                            goto AlternationBacktrack;
                        }
                        goto CaptureBacktrack;
                        LoopEnd1:;
                    //}
                    
                    // Optional (greedy).
                    {
                        startingStackpos = stackpos;
                        loop_iteration2 = 0;
                        
                        LoopBody2:
                        Utilities.StackPush(ref base.runstack!, ref stackpos, base.Crawlpos(), pos);
                        
                        loop_iteration2++;
                        
                        // Match '/'.
                        if (slice.IsEmpty || slice[0] != '/')
                        {
                            goto LoopIterationNoMatch2;
                        }
                        
                        // Match any character other than a whitespace character atomically any number of times.
                        {
                            int iteration3 = 1;
                            while ((uint)iteration3 < (uint)slice.Length && !char.IsWhiteSpace(slice[iteration3]))
                            {
                                iteration3++;
                            }
                            
                            slice = slice.Slice(iteration3);
                            pos += iteration3;
                        }
                        
                        
                        // The loop has an upper bound of 1. Continue iterating greedily if it hasn't yet been reached.
                        if (loop_iteration2 == 0)
                        {
                            goto LoopBody2;
                        }
                        goto LoopEnd2;
                        
                        // The loop iteration failed. Put state back to the way it was before the iteration.
                        LoopIterationNoMatch2:
                        if (--loop_iteration2 < 0)
                        {
                            // Unable to match the remainder of the expression after exhausting the loop.
                            goto LoopBacktrack1;
                        }
                        pos = base.runstack![--stackpos];
                        UncaptureUntil(base.runstack![--stackpos]);
                        slice = inputSpan.Slice(pos);
                        LoopEnd2:
                        stackpos = startingStackpos; // Ensure any remaining backtracking state is removed.
                    }
                    
                    // The input matched.
                    base.runtextpos = pos;
                    base.Capture(0, matchStart, pos);
                    return true;
                    
                    // <summary>Undo captures until it reaches the specified capture position.</summary>
                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    void UncaptureUntil(int capturePosition)
                    {
                        while (base.Crawlpos() > capturePosition)
                        {
                            base.Uncapture();
                        }
                    }
                }
            }
        }

    }
    
    /// <summary>Helper methods used by generated <see cref="Regex"/>-derived implementations.</summary>
    [GeneratedCodeAttribute("System.Text.RegularExpressions.Generator", "10.0.14.37416")]
    file static class Utilities
    {
        /// <summary>Default timeout value set in <see cref="AppContext"/>, or <see cref="Regex.InfiniteMatchTimeout"/> if none was set.</summary>
        internal static readonly TimeSpan s_defaultTimeout = AppContext.GetData("REGEX_DEFAULT_MATCH_TIMEOUT") is TimeSpan timeout ? timeout : Regex.InfiniteMatchTimeout;
        
        /// <summary>Whether <see cref="s_defaultTimeout"/> is non-infinite.</summary>
        internal static readonly bool s_hasTimeout = s_defaultTimeout != Regex.InfiniteMatchTimeout;
        
        /// <summary>Pops 2 values from the backtracking stack.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static void StackPop(int[] stack, ref int pos, out int arg0, out int arg1)
        {
            arg0 = stack[--pos];
            arg1 = stack[--pos];
        }
        
        /// <summary>Pushes 1 value onto the backtracking stack.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static void StackPush(ref int[] stack, ref int pos, int arg0)
        {
            // If there's space available for the value, store it.
            int[] s = stack;
            int p = pos;
            if ((uint)p < (uint)s.Length)
            {
                s[p] = arg0;
                pos++;
                return;
            }
        
            // Otherwise, resize the stack to make room and try again.
            WithResize(ref stack, ref pos, arg0);
        
            // <summary>Resize the backtracking stack array and push 1 value onto the stack.</summary>
            [MethodImpl(MethodImplOptions.NoInlining)]
            static void WithResize(ref int[] stack, ref int pos, int arg0)
            {
                Array.Resize(ref stack, (pos + 0) * 2);
                StackPush(ref stack, ref pos, arg0);
            }
        }
        
        /// <summary>Pushes 2 values onto the backtracking stack.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static void StackPush(ref int[] stack, ref int pos, int arg0, int arg1)
        {
            // If there's space available for all 2 values, store them.
            int[] s = stack;
            int p = pos;
            if ((uint)(p + 1) < (uint)s.Length)
            {
                s[p] = arg0;
                s[p + 1] = arg1;
                pos += 2;
                return;
            }
        
            // Otherwise, resize the stack to make room and try again.
            WithResize(ref stack, ref pos, arg0, arg1);
        
            // <summary>Resize the backtracking stack array and push 2 values onto the stack.</summary>
            [MethodImpl(MethodImplOptions.NoInlining)]
            static void WithResize(ref int[] stack, ref int pos, int arg0, int arg1)
            {
                Array.Resize(ref stack, (pos + 1) * 2);
                StackPush(ref stack, ref pos, arg0, arg1);
            }
        }
        
        /// <summary>Pushes 3 values onto the backtracking stack.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static void StackPush(ref int[] stack, ref int pos, int arg0, int arg1, int arg2)
        {
            // If there's space available for all 3 values, store them.
            int[] s = stack;
            int p = pos;
            if ((uint)(p + 2) < (uint)s.Length)
            {
                s[p] = arg0;
                s[p + 1] = arg1;
                s[p + 2] = arg2;
                pos += 3;
                return;
            }
        
            // Otherwise, resize the stack to make room and try again.
            WithResize(ref stack, ref pos, arg0, arg1, arg2);
        
            // <summary>Resize the backtracking stack array and push 3 values onto the stack.</summary>
            [MethodImpl(MethodImplOptions.NoInlining)]
            static void WithResize(ref int[] stack, ref int pos, int arg0, int arg1, int arg2)
            {
                Array.Resize(ref stack, (pos + 2) * 2);
                StackPush(ref stack, ref pos, arg0, arg1, arg2);
            }
        }
        
        /// <summary>Supports searching for characters in or not in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".</summary>
        internal static readonly SearchValues<char> s_asciiLetters = SearchValues.Create("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
        
        /// <summary>Supports searching for characters in or not in "-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".</summary>
        internal static readonly SearchValues<char> s_asciiLettersAndDigitsAndDash = SearchValues.Create("-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
    }
}
