name: Validate

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

env:
  DOTNET_VERSION: 10.0.x
  SOLUTION_PATH: XFEExtension.slnx
  PROJECT_PATH: XFEExtension.NetCore/XFEExtension.NetCore.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore -p:GeneratePackageOnBuild=false -p:ContinuousIntegrationBuild=true
